Vagrant.configure("2") do |config|

    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.manage_guest = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = true
  
    config.vm.define "k8s-master" do |master|
  
      master.vm.box = "ubuntu/focal64" 
      master.vm.hostname = "k8s-master"
  
      master.vm.network "private_network", ip: "192.168.56.3"
  
      master.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
        vb.memory = "4096" 
        vb.cpus = 4   
      end
  
      master.vm.provision "shell" do |shell|
        shell.path = "shell/master.sh"
      end
  
    end
  
    (1..2).each do |i|
      config.vm.define "k8s-worker-#{i}" do |worker|
  
        worker.vm.box = "ubuntu/focal64" 
        worker.vm.hostname = "k8s-worker-#{i}"
        
        worker.vm.network "private_network", ip: "192.168.56.#{i + 3}"
        
        worker.vm.provider "virtualbox" do |vb|
          vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]
          vb.memory = "2048" 
          vb.cpus = 1
        end
  
        worker.vm.provision "shell" do |shell|
          shell.path = "shell/worker.sh"
        end
  
      end
    end
  end