---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - sustain-kube.com
  resources:
  - carbonestimators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sustain-kube.com
  resources:
  - carbonestimators/finalizers
  verbs:
  - update
- apiGroups:
  - sustain-kube.com
  resources:
  - carbonestimators/status
  verbs:
  - get
  - patch
  - update
